export const midiNotes = [
  "C-1",
  "C#-1",
  "D-1",
  "D#-1",
  "E-1",
  "F-1",
  "F#-1",
  "G-1",
  "G#-1",
  "A-1",
  "A#-1",
  "B-1",
  "C0",
  "C#0",
  "D0",
  "D#0",
  "E0",
  "F0",
  "F#0",
  "G0",
  "G#0",
  "A0",
  "A#0",
  "B0",
  "C1",
  "C#1",
  "D1",
  "D#1",
  "E1",
  "F1",
  "F#1",
  "G1",
  "G#1",
  "A1",
  "A#1",
  "B1",
  "C2",
  "C#2",
  "D2",
  "D#2",
  "E2",
  "F2",
  "F#2",
  "G2",
  "G#2",
  "A2",
  "A#2",
  "B2",
  "C3",
  "C#3",
  "D3",
  "D#3",
  "E3",
  "F3",
  "F#3",
  "G3",
  "G#3",
  "A3",
  "A#3",
  "B3",
  "C4",
  "C#4",
  "D4",
  "D#4",
  "E4",
  "F4",
  "F#4",
  "G4",
  "G#4",
  "A4",
  "A#4",
  "B4",
  "C5",
  "C#5",
  "D5",
  "D#5",
  "E5",
  "F5",
  "F#5",
  "G5",
  "G#5",
  "A5",
  "A#5",
  "B5",
  "C6",
  "C#6",
  "D6",
  "D#6",
  "E6",
  "F6",
  "F#6",
  "G6",
  "G#6",
  "A6",
  "A#6",
  "B6",
  "C7",
  "C#7",
  "D7",
  "D#7",
  "E7",
  "F7",
  "F#7",
  "G7",
  "G#7",
  "A7",
  "A#7",
  "B7",
  "C8",
  "C#8",
  "D8",
  "D#8",
  "E8",
  "F8",
  "F#8",
  "G8",
  "G#8",
  "A8",
  "A#8",
  "B8",
  "C9",
  "C#9",
  "D9",
  "D#9",
  "E9",
  "F9",
  "F#9",
  "G9",
];

export const midiCC = [
  "Bank Select",
  "Modulation Wheel",
  "Breath Controller",
  "Undefined",
  "Foot Controller",
  "Portamento Time",
  "Data Entry MSB",
  "Channel Volume",
  "Balance",
  "Undefined",
  "Pan",
  "Expression Controller",
  "Effect Control 1",
  "Effect Control 2",
  "Undefined",
  "Undefined",
  "General Purpose Controller 1",
  "General Purpose Controller 2",
  "General Purpose Controller 3",
  "General Purpose Controller 4",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Bank Select (LSB)",
  "Modulation Wheel (LSB)",
  "Breath Controller (LSB)",
  "Undefined",
  "Foot Controller (LSB)",
  "Portamento Time (LSB)",
  "Data Entry (LSB)",
  "Channel Volume (LSB)",
  "Balance (LSB)",
  "Undefined",
  "Pan (LSB)",
  "Expression Controller (LSB)",
  "Effect Control 1 (LSB)",
  "Effect Control 2 (LSB)",
  "Undefined",
  "Undefined",
  "General Purpose Controller 1 (LSB)",
  "General Purpose Controller 2 (LSB)",
  "General Purpose Controller 3 (LSB)",
  "General Purpose Controller 4 (LSB)",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Sustain Pedal (on/off)",
  "Portamento (on/off)",
  "Sostenuto (on/off)",
  "Soft Pedal (on/off)",
  "Legato Footswitch",
  "Hold 2",
  "Sound Controller 1 (Sound Variation)",
  "Sound Controller 2 (Timbre)",
  "Sound Controller 3 (Release Time)",
  "Sound Controller 4 (Attack Time)",
  "Sound Controller 5 (Brightness)",
  "Sound Controller 6",
  "Sound Controller 7",
  "Sound Controller 8",
  "Sound Controller 9",
  "Sound Controller 10",
  "General Purpose Controller 5",
  "General Purpose Controller 6",
  "General Purpose Controller 7",
  "General Purpose Controller 8",
  "Portamento Control",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Effects 1 Depth (Reverb Send Level)",
  "Effects 2 Depth (Tremolo Depth)",
  "Effects 3 Depth (Chorus Send Level)",
  "Effects 4 Depth (Celeste/Detune)",
  "Effects 5 Depth (Phaser Depth)",
  "Data Increment",
  "Data Decrement",
  "NRPN LSB",
  "NRPN MSB",
  "RPN LSB",
  "RPN MSB",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "Undefined",
  "All Sound Off",
  "Reset All Controllers",
  "Local Control (on/off)",
  "All Notes Off",
  "Omni Mode Off",
  "Omni Mode On",
  "Mono Mode On",
  "Poly Mode On",
];
